install:
  - set PATH=C:\msys64\usr\bin;%PATH%
  - bash -lc "curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
  - bash -lc "curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig"
  - bash -lc "pacman-key --init"
  - bash -lc "pacman-key --populate msys2"
  - bash -lc "pacman-key --verify msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig"
  - bash -lc "pacman --ask 20 -U msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
  - ps: Get-Process | Where-Object {$_.path -like 'C:\msys64*'} | Stop-Process
  - C:\msys64\usr\bin\pacman -Rc --noconfirm mingw-w64-i686-gcc-ada mingw-w64-i686-gcc-objc mingw-w64-x86_64-gcc-ada mingw-w64-x86_64-gcc-objc
  - bash -lc "pacman --needed --ask 20 -Syu"
  - bash -lc "pacman --needed --ask 20 -Sy"
  - bash -lc "pacman --noconfirm -S base-devel"
  - bash -lc "pacman --noconfirm -S msys2-devel"
  - bash -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain"
  - bash -lc "pacman --noconfirm -S mingw-w64-x86_64-pcre"
  - bash -lc "pacman --noconfirm -S msys2-runtime"
  - bash -lc "pacman --noconfirm -S isl"
# can not starts with %
#  - git submodule update --init
  - curl -L -o setup-sbvmidi.exe https://bitbucket.org/springbeats/sbvmidi/downloads/sbvmidi-setup-1.0.2.exe
  - dir
  - setup-sbvmidi.exe /SILENT
#  - C:\msys64\usr\bin\pacman-key --verify msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig
  - C:\msys64\usr\bin\pacman -Syyuu --noconfirm
  - C:\msys64\usr\bin\pacman -Suu --noconfirm
  - C:\msys64\usr\bin\pacman -S --noconfirm --needed mingw-w64-i686-gcc mingw-w64-x86_64-gcc
  - C:\msys64\usr\bin\pacman -Sc --noconfirm
  - C:\msys64\usr\bin\pacman -Ss --noconfirm boost
  - C:\msys64\usr\bin\pacman -Ss --noconfirm autoconf
  - C:\msys64\usr\bin\pacman -Ss --noconfirm automake
  - C:\msys64\usr\bin\pacman -Ss --noconfirm libtool
  - C:\msys64\usr\bin\pacman -Ss --noconfirm gettext
  - C:\msys64\usr\bin\pacman -S --noconfirm --needed
      mingw-w64-x86_64-boost autoconf mingw-w64-x86_64-libtool automake1.15 mingw-w64-x86_64-gettext

build_script:
  - dir C:\
  - dir C:\msys64
  - dir C:\msys64\usr\bin
  - dir C:\msys64\opt
  - dir C:\msys64\mingw64
  - dir c:\msys64\mingw64\bin
  - dir C:\msys64\mingw64\x86_64-w64-mingw32
  - dir C:\msys64\mingw64\x86_64-w64-mingw32\bin
  - dir C:\mingw-w64
  - dir C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin
  - dir C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\opt\bin
  - SET PATH=C:\mingw-w64\bin;C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%	
  - echo "%PATH%"
  - path
  - bash -c "env"
  - bash -c pwd
  - bash -c ls
  - bash -c "#aclocal -I m4 --install"
  - bash -c "#automake --add-missing -f"
  - bash -c "#autopoint -f"
  - bash -c "#libtoolize -i -f"
  - bash -c "#autoconf --add-missing"
  - bash -c "mkdir -p config"
  - bash -c "touch config/config.rpath"
  - bash -c "autoreconf -i -f"
  - bash -c "./configure"
  - bash -c make
  - bash -c "make check"
  - bash -c "make distcheck"
